[tools]
node = "lts"
bun = "latest"
rust = "latest"

python = "latest"
uv = "latest"
ruff = "latest"

[hooks]
postinstall = "corepack enable pnpm"

[env]
MISE_NODE_DEFAULT_PACKAGES_FILE = "~/.config/mise/default-npm-packages"
