[tools]
node = "lts"
bun = "latest"
rust = { version = "latest", components = "rust-analyzer" }
python = "latest"
uv = "latest"
ruff = "latest"

[env]
MISE_NODE_DEFAULT_PACKAGES_FILE = "~/.config/mise/default-npm-packages"
