theme = "beans"

[editor]
line-number = "relative"
bufferline = "always"
mouse = false
popup-border = "all"
cursorline = true

[editor.inline-diagnostics]
cursor-line = "error"

[editor.statusline]
left = ["mode", "spacer", "version-control"]
center = ["spinner"]
right = ["diagnostics", "position", "file-encoding", "file-base-name"]

mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[editor.file-picker]
hidden = false

[editor.whitespace.render]
tab = "all"

[editor.whitespace.characters]
space = "·"
tab = "→"

# keybind
[keys.normal]
C-s = ":w"

[keys.insert]
j = { k = "normal_mode" }
