theme = "gyaru"

[editor]
line-number = "relative"
mouse = false
popup-border = "all"
cursorline = true
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "error"

[editor.statusline]
left = [
  "mode",
  "file-name",
  "read-only-indicator",
  # "file-modification-indicator",
]
right = [
  "diagnostics",
  "spinner",
  # "selections",
  # "position",
  # "separator",
  "file-encoding",
]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[editor.file-picker]
hidden = false

[editor.whitespace.render]
tab = "all"
space = "all"

[editor.whitespace.characters]
space = "·"
tab = "→"

[keys.normal]
C-s = ":w"
C-r = ":config-reload"
C-y = ["yank_to_clipboard"]
C-g = ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w90% -h60% -E lazygit"

[keys.insert]
j = { k = "normal_mode" }
