shell = "zsh"

apply = ["defer"]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

[templates]
defer = "{{ hooks | get: \"pre\" | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks | get: \"post\" | nl }}"

[plugins.zsh-syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'

[plugins.zsh-abbr]
github = "olets/zsh-abbr"

# See the documentation for more https://github.com/rossmacarthur/sheldon#readme
