start-at-login = true
default-root-container-layout = 'accordion'

[gaps]
inner.horizontal = 6
inner.vertical = 6
outer.left = 6
outer.bottom = 6
outer.top = 6
outer.right = 6

[[on-window-detected]]
if.app-id="com.mitchellh.ghostty"
run= ["layout tiling"]

[[on-window-detected]]
if.app-id="com.1password.1password"
run= ["layout floating"]

[mode.main.binding]
# https://nikitabobko.github.io/AeroSpace/commands#focus
ctrl-h = 'focus left'
ctrl-l = 'focus right'

# https://nikitabobko.github.io/AeroSpace/commands#move
ctrl-shift-h = 'move left'
ctrl-shift-l = 'move right'

# https://nikitabobko.github.io/AeroSpace/commands#resize
ctrl-minus = 'resize smart -50'
ctrl-equal = 'resize smart +50'
ctrl-f = 'fullscreen'
